# 配置freemarker
spring:
  freemarker:
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    #    自动添加后缀
    suffix: .ftl
    #    模板更新时间
    template_update_delay: 1
    templateEncoding: UTF-8
    template-loader-path: classpath:/templates/
    #    设置全局数字格式：去除逗号
    settings:
      number_format: computer